# -*- coding: utf-8 -*-
"""BasicPython.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-TzzhTF52MTfUOYbOuYeg46AfeWjbIP6

#Basic Python Program

###Arithmetic Operation
"""

a=5
b=6
c=a*b
print(c)

"""###IF Condition"""

a=20
b=20
c=5
if (a<b):
  print("a is less than b")
elif (a==b):
  print("a is equal to b")
  print("a is not less than b")
  if (c<b):
    print("c is less than b")
else:
  print("a is not less than b")

"""###While"""

i=0
while (i<=9):
  print(i)
  i+=1 #i=i+1

"""###For"""

for i in range(11,0,-1):
  print(i)